// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: guilds.sql

package db

import (
	"context"
	"database/sql"
)

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO config (discord_guild_id, command_channel_id,
                    officer_role_id, guild_member_role_id, mercenary_role_id)
VALUES (?, ?, ?, ?, ?)
ON DUPLICATE KEY UPDATE
    command_channel_id   = VALUES(command_channel_id),
    officer_role_id      = VALUES(officer_role_id),
    guild_member_role_id = VALUES(guild_member_role_id),
    mercenary_role_id    = VALUES(mercenary_role_id)
`

type UpsertConfigParams struct {
	DiscordGuildID    string         `db:"discord_guild_id" json:"discord_guild_id"`
	CommandChannelID  sql.NullString `db:"command_channel_id" json:"command_channel_id"`
	OfficerRoleID     sql.NullString `db:"officer_role_id" json:"officer_role_id"`
	GuildMemberRoleID sql.NullString `db:"guild_member_role_id" json:"guild_member_role_id"`
	MercenaryRoleID   sql.NullString `db:"mercenary_role_id" json:"mercenary_role_id"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfig,
		arg.DiscordGuildID,
		arg.CommandChannelID,
		arg.OfficerRoleID,
		arg.GuildMemberRoleID,
		arg.MercenaryRoleID,
	)
	return err
}

const upsertGuild = `-- name: UpsertGuild :exec
INSERT INTO guilds (discord_guild_id, name)
VALUES (?, ?)
ON DUPLICATE KEY UPDATE
    name = COALESCE(VALUES(name), name)
`

type UpsertGuildParams struct {
	DiscordGuildID string         `db:"discord_guild_id" json:"discord_guild_id"`
	Name           sql.NullString `db:"name" json:"name"`
}

func (q *Queries) UpsertGuild(ctx context.Context, arg UpsertGuildParams) error {
	_, err := q.db.ExecContext(ctx, upsertGuild, arg.DiscordGuildID, arg.Name)
	return err
}
