// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type MemberExceptionsType string

const (
	MemberExceptionsTypeVacation MemberExceptionsType = "vacation"
	MemberExceptionsTypeExclude  MemberExceptionsType = "exclude"
)

func (e *MemberExceptionsType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberExceptionsType(s)
	case string:
		*e = MemberExceptionsType(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberExceptionsType: %T", src)
	}
	return nil
}

type NullMemberExceptionsType struct {
	MemberExceptionsType MemberExceptionsType `json:"member_exceptions_type"`
	Valid                bool                 `json:"valid"` // Valid is true if MemberExceptionsType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberExceptionsType) Scan(value interface{}) error {
	if value == nil {
		ns.MemberExceptionsType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberExceptionsType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberExceptionsType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberExceptionsType), nil
}

type WarJobsStatus string

const (
	WarJobsStatusQueued     WarJobsStatus = "queued"
	WarJobsStatusProcessing WarJobsStatus = "processing"
	WarJobsStatusDone       WarJobsStatus = "done"
	WarJobsStatusCanceled   WarJobsStatus = "canceled"
	WarJobsStatusError      WarJobsStatus = "error"
)

func (e *WarJobsStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WarJobsStatus(s)
	case string:
		*e = WarJobsStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WarJobsStatus: %T", src)
	}
	return nil
}

type NullWarJobsStatus struct {
	WarJobsStatus WarJobsStatus `json:"war_jobs_status"`
	Valid         bool          `json:"valid"` // Valid is true if WarJobsStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWarJobsStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WarJobsStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WarJobsStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWarJobsStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WarJobsStatus), nil
}

type Config struct {
	DiscordGuildID string `db:"discord_guild_id" json:"discord_guild_id"`
	// Role required to manage other members information, add/update wars, etc.
	OfficerRoleID sql.NullString `db:"officer_role_id" json:"officer_role_id"`
	// Role required for a member to update their own information
	GuildMemberRoleID sql.NullString `db:"guild_member_role_id" json:"guild_member_role_id"`
	// Role for mercenary members
	MercenaryRoleID sql.NullString `db:"mercenary_role_id" json:"mercenary_role_id"`
	// Channel where commands and results are posted
	CommandChannelID sql.NullString `db:"command_channel_id" json:"command_channel_id"`
	Timezone         string         `db:"timezone" json:"timezone"`
	UpdatedAt        time.Time      `db:"updated_at" json:"updated_at"`
}

type Guild struct {
	ID             uint64         `db:"id" json:"id"`
	DiscordGuildID string         `db:"discord_guild_id" json:"discord_guild_id"`
	Name           sql.NullString `db:"name" json:"name"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
}

type MemberException struct {
	ID              uint64               `db:"id" json:"id"`
	DiscordGuildID  string               `db:"discord_guild_id" json:"discord_guild_id"`
	RosterMemberID  uint64               `db:"roster_member_id" json:"roster_member_id"`
	Type            MemberExceptionsType `db:"type" json:"type"`
	StartDate       time.Time            `db:"start_date" json:"start_date"`
	EndDate         time.Time            `db:"end_date" json:"end_date"`
	Reason          sql.NullString       `db:"reason" json:"reason"`
	CreatedByUserID string               `db:"created_by_user_id" json:"created_by_user_id"`
	CreatedAt       time.Time            `db:"created_at" json:"created_at"`
}

type MemberTeam struct {
	ID             uint64    `db:"id" json:"id"`
	RosterMemberID uint64    `db:"roster_member_id" json:"roster_member_id"`
	TeamID         uint64    `db:"team_id" json:"team_id"`
	AssignedAt     time.Time `db:"assigned_at" json:"assigned_at"`
}

type RosterMember struct {
	ID             uint64 `db:"id" json:"id"`
	DiscordGuildID string `db:"discord_guild_id" json:"discord_guild_id"`
	// Discord user ID for this member
	DiscordUserID sql.NullString `db:"discord_user_id" json:"discord_user_id"`
	// BDO family name
	FamilyName string `db:"family_name" json:"family_name"`
	// Cached Discord display name
	DisplayName sql.NullString `db:"display_name" json:"display_name"`
	// BDO class name
	Class sql.NullString `db:"class" json:"class"`
	// Class specialization: succession, awakening, or ascension
	Spec sql.NullString `db:"spec" json:"spec"`
	// Attack Power
	Ap sql.NullInt32 `db:"ap" json:"ap"`
	// Awakening Attack Power
	Aap sql.NullInt32 `db:"aap" json:"aap"`
	// Defense Power
	Dp sql.NullInt32 `db:"dp" json:"dp"`
	// Evasion stat
	Evasion sql.NullInt32 `db:"evasion" json:"evasion"`
	// Damage Reduction
	Dr sql.NullInt32 `db:"dr" json:"dr"`
	// Damage Reduction Rate percentage
	Drr sql.NullString `db:"drr" json:"drr"`
	// Accuracy stat
	Accuracy sql.NullInt32 `db:"accuracy" json:"accuracy"`
	// HP stat
	Hp sql.NullInt32 `db:"hp" json:"hp"`
	// Total Attack Power
	TotalAp sql.NullInt32 `db:"total_ap" json:"total_ap"`
	// Total Awakening Attack Power
	TotalAap sql.NullInt32 `db:"total_aap" json:"total_aap"`
	// Officer verified member meets required stat caps
	MeetsCap bool `db:"meets_cap" json:"meets_cap"`
	// Member K/D stats excluded from guild overall K/D calculations
	IsException bool      `db:"is_exception" json:"is_exception"`
	IsActive    bool      `db:"is_active" json:"is_active"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at" json:"updated_at"`
}

type Team struct {
	ID             uint64    `db:"id" json:"id"`
	DiscordGuildID string    `db:"discord_guild_id" json:"discord_guild_id"`
	Code           string    `db:"code" json:"code"`
	DisplayName    string    `db:"display_name" json:"display_name"`
	IsActive       bool      `db:"is_active" json:"is_active"`
	CreatedAt      time.Time `db:"created_at" json:"created_at"`
}

type War struct {
	ID             uint64         `db:"id" json:"id"`
	DiscordGuildID string         `db:"discord_guild_id" json:"discord_guild_id"`
	JobID          uint64         `db:"job_id" json:"job_id"`
	WarDate        time.Time      `db:"war_date" json:"war_date"`
	Label          sql.NullString `db:"label" json:"label"`
	IsExcluded     bool           `db:"is_excluded" json:"is_excluded"`
	CreatedAt      time.Time      `db:"created_at" json:"created_at"`
}

type WarJob struct {
	ID                uint64         `db:"id" json:"id"`
	DiscordGuildID    string         `db:"discord_guild_id" json:"discord_guild_id"`
	RequestChannelID  string         `db:"request_channel_id" json:"request_channel_id"`
	RequestMessageID  string         `db:"request_message_id" json:"request_message_id"`
	RequestedByUserID string         `db:"requested_by_user_id" json:"requested_by_user_id"`
	Status            WarJobsStatus  `db:"status" json:"status"`
	Error             sql.NullString `db:"error" json:"error"`
	CreatedAt         time.Time      `db:"created_at" json:"created_at"`
	StartedAt         sql.NullTime   `db:"started_at" json:"started_at"`
	FinishedAt        sql.NullTime   `db:"finished_at" json:"finished_at"`
}

type WarJobAttachment struct {
	ID                  uint64         `db:"id" json:"id"`
	JobID               uint64         `db:"job_id" json:"job_id"`
	Idx                 int32          `db:"idx" json:"idx"`
	DiscordAttachmentID string         `db:"discord_attachment_id" json:"discord_attachment_id"`
	Filename            string         `db:"filename" json:"filename"`
	ContentType         sql.NullString `db:"content_type" json:"content_type"`
	SizeBytes           sql.NullInt64  `db:"size_bytes" json:"size_bytes"`
	Url                 string         `db:"url" json:"url"`
	LocalPath           sql.NullString `db:"local_path" json:"local_path"`
}

type WarLine struct {
	ID              uint64         `db:"id" json:"id"`
	WarID           uint64         `db:"war_id" json:"war_id"`
	RosterMemberID  sql.NullInt64  `db:"roster_member_id" json:"roster_member_id"`
	OcrName         string         `db:"ocr_name" json:"ocr_name"`
	Kills           int32          `db:"kills" json:"kills"`
	Deaths          int32          `db:"deaths" json:"deaths"`
	MatchedName     sql.NullString `db:"matched_name" json:"matched_name"`
	MatchConfidence sql.NullString `db:"match_confidence" json:"match_confidence"`
	// BDO class name
	Class sql.NullString `db:"class" json:"class"`
	// Class specialization
	Spec      sql.NullString `db:"spec" json:"spec"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
}
