// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateRosterMember(ctx context.Context, arg CreateRosterMemberParams) (sql.Result, error)
	CreateTeam(ctx context.Context, arg CreateTeamParams) (sql.Result, error)
	CreateWar(ctx context.Context, arg CreateWarParams) (sql.Result, error)
	CreateWarJob(ctx context.Context, arg CreateWarJobParams) (sql.Result, error)
	CreateWarLine(ctx context.Context, arg CreateWarLineParams) error
	DeactivateTeam(ctx context.Context, arg DeactivateTeamParams) (sql.Result, error)
	GetRosterMemberByFamilyName(ctx context.Context, arg GetRosterMemberByFamilyNameParams) (uint64, error)
	GetTeamByCodeOrName(ctx context.Context, arg GetTeamByCodeOrNameParams) (GetTeamByCodeOrNameRow, error)
	GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (GetTeamByNameRow, error)
	GetWarStats(ctx context.Context, discordGuildID string) ([]GetWarStatsRow, error)
	ReactivateTeam(ctx context.Context, id uint64) (sql.Result, error)
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) error
	UpsertGuild(ctx context.Context, arg UpsertGuildParams) error
}

var _ Querier = (*Queries)(nil)
