// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: teams.sql

package db

import (
	"context"
	"database/sql"
)

const createTeam = `-- name: CreateTeam :execresult
INSERT INTO teams (discord_guild_id, code, display_name, is_active)
VALUES (?, ?, ?, 1)
`

type CreateTeamParams struct {
	DiscordGuildID string `db:"discord_guild_id" json:"discord_guild_id"`
	Code           string `db:"code" json:"code"`
	DisplayName    string `db:"display_name" json:"display_name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createTeam, arg.DiscordGuildID, arg.Code, arg.DisplayName)
}

const deactivateTeam = `-- name: DeactivateTeam :execresult
UPDATE teams
SET is_active = 0
WHERE discord_guild_id = ? AND display_name = ? AND is_active = 1
`

type DeactivateTeamParams struct {
	DiscordGuildID string `db:"discord_guild_id" json:"discord_guild_id"`
	DisplayName    string `db:"display_name" json:"display_name"`
}

func (q *Queries) DeactivateTeam(ctx context.Context, arg DeactivateTeamParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deactivateTeam, arg.DiscordGuildID, arg.DisplayName)
}

const getTeamByCodeOrName = `-- name: GetTeamByCodeOrName :one
SELECT id, is_active 
FROM teams
WHERE discord_guild_id = ? AND (code = ? OR display_name = ?)
`

type GetTeamByCodeOrNameParams struct {
	DiscordGuildID string `db:"discord_guild_id" json:"discord_guild_id"`
	Code           string `db:"code" json:"code"`
	DisplayName    string `db:"display_name" json:"display_name"`
}

type GetTeamByCodeOrNameRow struct {
	ID       uint64 `db:"id" json:"id"`
	IsActive bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) GetTeamByCodeOrName(ctx context.Context, arg GetTeamByCodeOrNameParams) (GetTeamByCodeOrNameRow, error) {
	row := q.db.QueryRowContext(ctx, getTeamByCodeOrName, arg.DiscordGuildID, arg.Code, arg.DisplayName)
	var i GetTeamByCodeOrNameRow
	err := row.Scan(&i.ID, &i.IsActive)
	return i, err
}

const getTeamByName = `-- name: GetTeamByName :one
SELECT id, code, display_name, is_active
FROM teams
WHERE discord_guild_id = ? AND display_name = ?
`

type GetTeamByNameParams struct {
	DiscordGuildID string `db:"discord_guild_id" json:"discord_guild_id"`
	DisplayName    string `db:"display_name" json:"display_name"`
}

type GetTeamByNameRow struct {
	ID          uint64 `db:"id" json:"id"`
	Code        string `db:"code" json:"code"`
	DisplayName string `db:"display_name" json:"display_name"`
	IsActive    bool   `db:"is_active" json:"is_active"`
}

func (q *Queries) GetTeamByName(ctx context.Context, arg GetTeamByNameParams) (GetTeamByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getTeamByName, arg.DiscordGuildID, arg.DisplayName)
	var i GetTeamByNameRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.DisplayName,
		&i.IsActive,
	)
	return i, err
}

const reactivateTeam = `-- name: ReactivateTeam :execresult
UPDATE teams
SET is_active = 1
WHERE id = ?
`

func (q *Queries) ReactivateTeam(ctx context.Context, id uint64) (sql.Result, error) {
	return q.db.ExecContext(ctx, reactivateTeam, id)
}
