// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: wars.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createRosterMember = `-- name: CreateRosterMember :execresult
INSERT INTO roster_members (discord_guild_id, family_name, is_active)
VALUES (?, ?, 1)
`

type CreateRosterMemberParams struct {
	DiscordGuildID string `db:"discord_guild_id" json:"discord_guild_id"`
	FamilyName     string `db:"family_name" json:"family_name"`
}

func (q *Queries) CreateRosterMember(ctx context.Context, arg CreateRosterMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRosterMember, arg.DiscordGuildID, arg.FamilyName)
}

const createWar = `-- name: CreateWar :execresult
INSERT INTO wars (discord_guild_id, job_id, war_date, label)
VALUES (?, ?, ?, ?)
`

type CreateWarParams struct {
	DiscordGuildID string         `db:"discord_guild_id" json:"discord_guild_id"`
	JobID          uint64         `db:"job_id" json:"job_id"`
	WarDate        time.Time      `db:"war_date" json:"war_date"`
	Label          sql.NullString `db:"label" json:"label"`
}

func (q *Queries) CreateWar(ctx context.Context, arg CreateWarParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWar,
		arg.DiscordGuildID,
		arg.JobID,
		arg.WarDate,
		arg.Label,
	)
}

const createWarJob = `-- name: CreateWarJob :execresult
INSERT INTO war_jobs (discord_guild_id, request_channel_id, request_message_id, 
                      requested_by_user_id, status, started_at, finished_at)
VALUES (?, ?, ?, ?, 'done', NOW(), NOW())
`

type CreateWarJobParams struct {
	DiscordGuildID    string `db:"discord_guild_id" json:"discord_guild_id"`
	RequestChannelID  string `db:"request_channel_id" json:"request_channel_id"`
	RequestMessageID  string `db:"request_message_id" json:"request_message_id"`
	RequestedByUserID string `db:"requested_by_user_id" json:"requested_by_user_id"`
}

func (q *Queries) CreateWarJob(ctx context.Context, arg CreateWarJobParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWarJob,
		arg.DiscordGuildID,
		arg.RequestChannelID,
		arg.RequestMessageID,
		arg.RequestedByUserID,
	)
}

const createWarLine = `-- name: CreateWarLine :exec
INSERT INTO war_lines (war_id, roster_member_id, ocr_name, kills, deaths, matched_name)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreateWarLineParams struct {
	WarID          uint64         `db:"war_id" json:"war_id"`
	RosterMemberID sql.NullInt64  `db:"roster_member_id" json:"roster_member_id"`
	OcrName        string         `db:"ocr_name" json:"ocr_name"`
	Kills          int32          `db:"kills" json:"kills"`
	Deaths         int32          `db:"deaths" json:"deaths"`
	MatchedName    sql.NullString `db:"matched_name" json:"matched_name"`
}

func (q *Queries) CreateWarLine(ctx context.Context, arg CreateWarLineParams) error {
	_, err := q.db.ExecContext(ctx, createWarLine,
		arg.WarID,
		arg.RosterMemberID,
		arg.OcrName,
		arg.Kills,
		arg.Deaths,
		arg.MatchedName,
	)
	return err
}

const getRosterMemberByFamilyName = `-- name: GetRosterMemberByFamilyName :one
SELECT id FROM roster_members
WHERE discord_guild_id = ? AND LOWER(family_name) = LOWER(?)
LIMIT 1
`

type GetRosterMemberByFamilyNameParams struct {
	DiscordGuildID string `db:"discord_guild_id" json:"discord_guild_id"`
	LOWER          string `db:"LOWER" json:"LOWER"`
}

func (q *Queries) GetRosterMemberByFamilyName(ctx context.Context, arg GetRosterMemberByFamilyNameParams) (uint64, error) {
	row := q.db.QueryRowContext(ctx, getRosterMemberByFamilyName, arg.DiscordGuildID, arg.LOWER)
	var id uint64
	err := row.Scan(&id)
	return id, err
}

const getWarStats = `-- name: GetWarStats :many
SELECT 
    rm.family_name,
    COUNT(DISTINCT CASE WHEN w.id IS NOT NULL THEN w.id END) as total_wars,
    MAX(CASE WHEN w.id IS NOT NULL THEN w.war_date END) as most_recent_war,
    COALESCE(SUM(CASE WHEN w.id IS NOT NULL THEN wl.kills ELSE 0 END), 0) as total_kills,
    COALESCE(SUM(CASE WHEN w.id IS NOT NULL THEN wl.deaths ELSE 0 END), 0) as total_deaths
FROM roster_members rm
LEFT JOIN war_lines wl ON rm.id = wl.roster_member_id
LEFT JOIN wars w ON wl.war_id = w.id AND w.is_excluded = 0
WHERE rm.discord_guild_id = ? 
  AND rm.is_active = 1
GROUP BY rm.id, rm.family_name
ORDER BY rm.family_name
`

type GetWarStatsRow struct {
	FamilyName    string      `db:"family_name" json:"family_name"`
	TotalWars     int64       `db:"total_wars" json:"total_wars"`
	MostRecentWar interface{} `db:"most_recent_war" json:"most_recent_war"`
	TotalKills    interface{} `db:"total_kills" json:"total_kills"`
	TotalDeaths   interface{} `db:"total_deaths" json:"total_deaths"`
}

func (q *Queries) GetWarStats(ctx context.Context, discordGuildID string) ([]GetWarStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, getWarStats, discordGuildID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWarStatsRow{}
	for rows.Next() {
		var i GetWarStatsRow
		if err := rows.Scan(
			&i.FamilyName,
			&i.TotalWars,
			&i.MostRecentWar,
			&i.TotalKills,
			&i.TotalDeaths,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
